### ISSUE TITLE
Spaces in path not escaped

### ISSUE THREAD

**Issue by midwan** [JohnArcher/vscode-hollywood-mal#1]
Great work implementing this Extension!

I noticed that on Windows, the current example file for a Build Task, doesn't quite work.
The spaces in the path to the Hollywood executable are not escaped, so the task tries to execute `C:\Program` since that's where the first space shows up.

It might be better to break the `command` and the `args` in separate fields, instead:

```
"command": "${config:hollywood.exePath}",
            "args": ["${workspaceFolder}/${config:hollywood.mainFile}"],
```

The above works normally with the spaces in the path. It also looks a bit nicer, since you don't have one very long line in a single command. ;-)

**Comment by JohnArcher** [comment]
Thanks a lot, midwan!

In the dev branch I already mentioned a fix to this problem, but your solution is much better! Thanks a lot for the proper Pull Request, I will merge that tonight.

**Comment by midwan** [comment]
No problem, happy to help! :)
While playing with it yesterday, I noticed a few other things that you might want to know:
* The behavior depends on what Terminal you have selected in VSCode. If you're using the standard Command Prompt, it behaves differently than let's say, PowerShell7. Powershell 7 would complaing about the parameter in my case, but the command prompt worked.
* You can skip the `${workspaceFolder}/` part if you want. By default, that's where the script will run from anyway. This way you can get rid of even more text in the line, and that weird looking mix of forward and backward slashes.
* If you want to, you can specify the current working directory in a separate option of the command: see `cwd` in the documentation. I didn't have to do that, but it might be good to mention in the docs.

**Comment by JohnArcher** [comment]
Thanks for the additonal infos. Regarding `${workspaceFolder}/` I commented your PR.

I can't reproduce the PowerShell problem you have. How do you enable that? When I select the default shell in the Terminal View to Powershell and then run a task it works flawlessly and also the output looks normal (which means I don't see whether it uses PS or not):

![image](https://user-images.githubusercontent.com/990724/81869419-4e434d80-9574-11ea-897e-2c87833b2a7e.png)

`cwd`: Makes sense, will do.

**Comment by midwan** [comment]
The powershell problem only seemed to occur with PowerShell 7 (https://github.com/powershell/powershell) - Since this might be an issue there only, I think you don't have to worry about it, just keep it in mind in case someone else runs into it. ;)
