### ISSUE TITLE
Multiple exetype options need to be enclosed in quotes

### ISSUE THREAD

**Issue by midwan** [JohnArcher/vscode-hollywood-mal#28]
Thanks for the excellent work with this project! :)

I noticed that the `tasks.json` example does not quite work as-is, at least not for me (I'm using Powershell as the default terminal, but I also tried the `cmd` one, and got the same result).
The multiple platforms specification are separated by a pipe character (`|`), but Powershell interprets that and it fails, unless the whole thing is enclosed in quotes.

For example, this fails:
```-exetype win32|win64```

with the following error message:
```
win64: The term 'win64' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

but doing it like this, works:
``` -exetype "win32|win64"```

Accordingly, the `tasks.json` example in your documentation could be updated as follows:
```
        {
            "label": "Compile the currently opened Hollywood file to multiple targets ",
            "type": "shell",
            "command": "${config:hollywood.exePath}",
            "args": [
                "${file}",
                "-compile",
                "${fileBasenameNoExtension}",
                "-exetype",
                "'win32|win64|classic|morphos'"
            ]
        }
```

To ensure it works - I've only enclosed those options with a single quote.

Hope this helps!

**Comment by JohnArcher** [comment]
Hey @midwan , thanks a lot for your contribution! I will check this in detail later, I just wanted to get back to you and say sorry for my late response. I don't know what the problem is, but I don't get email notifications for _new_ issues, just if someone replys to existing ones etc. So I found you issue by accident now. :-(
