### ISSUE TITLE
Main text: Still Hollywood 9.1 is written

### ISSUE THREAD

**Issue by halle-saale** [JohnArcher/vscode-hollywood-mal#35]
In your main text, you have still written: "This extension adds support for Hollywood version 9.1 to...", which should now be 10.0.
Thanks for your development, little article publsihed:
https://www.amiga-news.de/en/news/AN-2024-01-00019-EN.html

**Comment by JohnArcher** [comment]
Thanks a lot for opening the issue, @halle-saale ! I will fix it tonight.

And also thanks for the news article! ♥
