### ISSUE TITLE
Feature request: recognition of functions

### ISSUE THREAD

**Issue by mrupp12bit** [JohnArcher/vscode-hollywood-mal#7]
Excellent work, I like it a lot!
Any chance to implement the recognition of functions, like it's done with JavaScript files?
![VSCode_FunctionsRecogniton](https://user-images.githubusercontent.com/38189288/107558957-b72b2500-6bdb-11eb-95cf-e2ac2a01020f.png)

**Comment by mrupp12bit** [comment]
It's probably something to do with this:
https://code.visualstudio.com/api/language-extensions/programmatic-language-features
(I couldn't really figure out how to do this, though.)

**Comment by JohnArcher** [comment]
Thanks for your research. Currently I am also digging into this. As far as I know I need to define a `DefinitionProvider` (https://code.visualstudio.com/api/references/vscode-api#DefinitionProvider). It is hard to find good documentation on this, but I think I found a solution (through examine other extensions). I hope to create a first prototype this weekend.

**Comment by mrupp12bit** [comment]
This is great news! I’m looking forward to testing it!

**Comment by JohnArcher** [comment]
Looks promising, right? Took some time to get it working and still _a lot_ to test and improve. This is just a prototype, but I finally know how to do it basically.

![Code_2021-02-21_15-38-16](https://user-images.githubusercontent.com/990724/108628455-662cf380-745b-11eb-9eac-de8ac436fdd7.png)

![Code_2021-02-21_15-38-37](https://user-images.githubusercontent.com/990724/108628458-6927e400-745b-11eb-9941-d37b17ac02cf.png)

![Code_2021-02-21_15-38-58](https://user-images.githubusercontent.com/990724/108628462-6cbb6b00-745b-11eb-904c-3ec07aaa220f.png)

**Comment by mrupp12bit** [comment]
VERY promising! Cool! Let me know if I can be of any help in testing things out...

**Comment by JohnArcher** [comment]
Will do, thanks a lot. We need a way that I can send/provide you a vsix file that you  install. The files are currently around 150 KB, so sending via mail would be no problem. Maybe you can PM me your mail address at the Hollywood forum?

**Comment by mrupp12bit** [comment]
done

**Comment by JohnArcher** [comment]
Just to let everyone know, work on this feature is progressing nicely and @mrupp12bit already got a first version to test, so it is very likely that this feature will be in the next release.

**Comment by JohnArcher** [comment]
Closed by 874a0e6655fa7663db67308277da75118e893203
