### ISSUE TITLE
[[test]] not recognized as string

### ISSUE THREAD

**Issue by mrupp12bit** [JohnArcher/vscode-hollywood-mal#9]
Here's another (hopefully a small) one:
Strings are perfectly recognized if they are enclosed in double quotes, but not if they are enclosed in double square brackets:

![image](https://user-images.githubusercontent.com/38189288/108414928-17017b80-722d-11eb-9e78-12cbcecdf936.png)

**Comment by JohnArcher** [comment]
Is this valid Hollywood syntax? I have never seen a string defined like that (in no programming language :-)).

**Comment by mrupp12bit** [comment]
I know, it looks strange but is perfectly valid. Here’s the doc entry describing it:

https://www.hollywood-mal.com/docs/html/hollywood/PrgTypeString.html

Using this notation you can have line breaks and even double quotes inside a string without escaping them with \.

**Comment by mrupp12bit** [comment]
The tricky thing here is probably to ensure everything inside the double square brackets is treated as a string, even if there are one or more double quotes present inside:

Right now, this can kind of "break" the string recognition:
![image](https://user-images.githubusercontent.com/38189288/108544028-28f32500-72e6-11eb-8925-2f9a9b51c1cc.png)

**Comment by mrupp12bit** [comment]
The whole thing is similar to the TypeScript notation of a string enclosed with `:
![image](https://user-images.githubusercontent.com/38189288/108544757-35c44880-72e7-11eb-87f4-fd2496a8b905.png)

**Comment by JohnArcher** [comment]
Holly cow, I wasn't aware of that. :-) Thanks for reporting and providing link and examples, I will have a look at this as well.

**Comment by JohnArcher** [comment]
First test looks promising, right? :-)

![image](https://user-images.githubusercontent.com/990724/108562648-77adb880-7300-11eb-8d98-79457647ab3f.png)

**Comment by mrupp12bit** [comment]
Excellent! Well done!
